# Generated by Django 5.1 on 2024-09-01 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_description_product_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='price_per_unit',
        ),
    ]
