# Generated by Django 5.0.2 on 2024-09-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_orderdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=254)),
                ('subject', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('message', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
